--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/03/2023 09:03:49
-- Server version: 8.0.32
-- Client version: 4.1
--


SET NAMES 'utf8';


INSERT INTO pandabudget.items(`INDEX`, items_INDEX, items_projet_INDEX, items_code, items_name, items_parent, items_quantity, items_unit, items_price_total, items_taxe, items_taxe_value, items_currency, items_last_edit_date) VALUES
(1, 1, 1, 'MACONNERIE', 'MACONNERIE', 'MUREXTERNE18M', 2, 900, 1800.00, 20.00, 360.00, 'EUEO', '2023-03-06'),
(2, 3, 2, 'MACONNERIE', 'MUREXTERNE18M', '_ROOT', 2, 900, 1800.00, 20.00, 360.00, 'EUEO', '2023-03-06');


INSERT INTO pandabudget.project(`INDEX`, PrOJECT_INDEX, PrOJECT_CODE, PrOJECT_NAME, PrOJECT_CREAT_DATE, PrOJECT_STATUS) VALUES
(1, 1, 'PANDA1', 'BUSSY', '2023-10-01', 'INPROGRESS'),
(2, 2, 'PANDA2', 'PONTAULT', '2023-03-01', 'INPROGRESS'),
(5, 5, 'PANDA5-2', 'THORIGNY', '2023-03-01', 'INPROGRESS');