'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PrevisionFlex.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_gray_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-gray-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_gray_30x30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-gray-30x30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_gray_50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-gray-50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_white_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-white-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property architech_gray_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("architech-gray-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property architech_white_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("architech-white-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bell_Gray_Claire_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bell_Gray_Claire_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bell_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bell_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bussy_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bussy_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calendrier_Gray_clair_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendrier_Gray_clair_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calendrier_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendrier_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_Gray_Clair_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_Gray_Clair_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_Gray_Clair_100x1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_Gray_Clair_100x1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Construction_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Construction-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ESTIMATOR_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ESTIMATOR-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Event_Gray_Claire_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Event_Gray_Claire_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Event_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Event_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help_Center_Gray_Clair_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_Center_Gray_Clair_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help_Center_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_Center_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_Gray_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_Gray_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_Gray_Clair_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_Gray_Clair_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invoice_gray_clair_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice-gray-clair-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invoice_white_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice-white-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poubelle_petite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poubelle-petite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reflech_25x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reflech_25x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_icon_128_Gray_Clair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_icon_128_Gray_Clair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_icon_128_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_icon_128_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tennis_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_detail_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-detail-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_detail_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-detail-25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_detail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-detail-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_sans_detail_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-sans-detail-15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_sans_detail_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-sans-detail-25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_sans_detail_251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-sans-detail-251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treeview_sans_detail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treeview-sans-detail-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_ronde_gray_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update-ronde-gray-100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_ronde_gray_30x30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update-ronde-gray-30x30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_ronde_gray_30x301() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update-ronde-gray-30x301", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_ronde_gray_30x302() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update-ronde-gray-30x302", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_Gray_Claire_100x100_inverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_Gray_Claire_100x100_inverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_White_100x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_White_100x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_White_100x100_inverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_White_100x100_inverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property veranda_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("veranda-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
